name: "Experiment: Deploy AWS Lambda JavaScript"

on:
  push:
    branches:
      - "experiment/build-lambda"

permissions:
  id-token: write
  contents: read

env:
  AWS_ROLE_ARN: arn:aws:iam::677276120513:role/practice-build-aws-lambda
  AWS_REGION: ap-northeast-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@4

      - name: Login
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Zip index.mjs
        run: zip -j lambda.zip src/index.mjs

      - name: Deploy to Lambda
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: practice-build-aws-lambda-function
          code-artifacts-dir: .
          runtime: nodejs20.x
          handler: index.handler
          role: ${{ env.AWS_ROLE_ARN }}